// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpzxkkjmbluyjaxyoxvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwenhra2ptYmx1eWpheHlveHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzQxMzIsImV4cCI6MjA2NDExMDEzMn0.gPy0_BL4cJnZw6OsYXJ7cjg6QsCwjKlwOp4Z3atYe64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);